name: 'Stump Nightly CI'

on:
  pull_request:
    branches:
      - nightly
  push:
    branches:
      - nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-changes-check:
    runs-on: [ubuntu-22.04]
    outputs:
      changes: ${{steps.filter.outputs.changes}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          base: 'nightly'
          filters: |
            apps:
              - './apps/desktop/src/**'
              - './apps/server/**'
              - './apps/web/**'
            core: ./core/**
            crates: ./crates/**
            docker: ./docker/**
            packages: ./packages/**
            root:
              - './.cargo/**'
              - './.dockerignore'
              - './.npmrc'
              - './Cargo.lock'
              - './Cargo.toml'
              - './lerna.json'
              - './package.json'
              - './rust-toolchain.toml'
              - './tsconfig.json'
              - './tsconfig.options.json'
              - './yarn.lock'
            workflow:
              - './.github/workflows/nightly.yml'
              - './.github/actions/build-docker/action.yml'

  nightly-docker-build:
    needs: code-changes-check
    if: "!contains(github.event.pull_request.head.ref, 'release/v') && needs.code-changes-check.outputs.changes != '[]'"
    name: Build docker image
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup and build docker image
        uses: ./.github/actions/build-docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: 'nightly'
          build-channel: 'nightly'
          push: ${{ github.event_name == 'push' }}
          archs: ${{ github.event_name == 'pull_request' && 'amd64' || 'arm64,amd64' }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
