name: Docker release

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - '.cargo/**'
      - '.dockerignore'
      - '.github/workflows/release_docker.yml'
      - '.npmrc'
      - 'apps/desktop/src/**'
      - 'apps/server/**'
      - 'apps/web/**'
      - 'core/**'
      - 'crates/**'
      - 'docker/**'
      - 'packages/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'lerna.json'
      - 'package.json'
      - 'rust-toolchain.toml'
      - 'tsconfig.json'
      - 'tsconfig.options.json'
      - 'yarn.lock'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        default: 'latest'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ inputs.tag || 'latest' }}
  cancel-in-progress: true

jobs:
  publish:
    uses: docker/github-builder/.github/workflows/build.yml@58cb9f5b71b1836d6f690c1e95effdeb9b98cb8a # v1
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: .
      file: ./docker/Dockerfile
      build-args: |
        GIT_REV=${{ github.sha }}
        BUILD_CHANNEL=stable
      labels: |
        org.opencontainers.image.revision=${{ github.sha }}
      cache: true
      cache-scope: stump
      cache-mode: max
      sign: 'false'
      meta-images: rubilmax/stump
      meta-tags: type=raw,value=${{ inputs.tag || 'latest' }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: rubilmax
          password: ${{ secrets.DOCKERHUB_TOKEN }}
